services:
  app:
    build: .
    container_name: tailresume-app
    ports:
      - "8080:80"             # map host 8080 → container 80
    volumes:
      - ./php:/var/www/html   # mount your PHP app for live edits (optional)
    networks:
      - appnet

networks:
  appnet:
