services:
  app:
    build: .
    container_name: tailresume-app
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./nginx:/etc/nginx
      - ./node/output.css:/var/www/html/assets/css/style.css
    depends_on:
      - tailwind

  tailwind:
    image: node:18-alpine
    container_name: tailresume-tailwind
    working_dir: /app
    volumes:
      - ./node:/app
    command: sh -c "npm install && npm run build"
